baseURL = "https://abuabdillah1.github.io/web/"
disqusShortname = ""
languageCode = "en-us"
paginate = "10"
theme = "mainroad"
title = "Abu Abdillah"
[Author]
avatar = "img/avatar.png"
bio = "Web Abu Abdillah"
name = "Abu Abdillah"
[Params]
authorbox = true
copyright = "Abu Abdillah"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
description = "Web Abu Abdillah"
googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700"
readmore = true
toc = true
[Params.logo]
image = "img/placeholder.png"
subtitle = "Mulia Mengikuti Manhaj Salaf"
title = "Abu Abdillah"
[Params.sidebar]
home = "right"
list = "left"
single = false
widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
[Params.style.vars]
fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
highlightColor = "#e22d30"
[Params.thumbnail]
visibility = ["list", "post"]
[Params.widgets]
categories_counter = false
recent_num = 5
tags_counter = false
[Params.widgets.social]
email = "abuabdillah408@gmail.com"
github = "abuabdillah1"
instagram = "username"
telegram = "ahadmyid"
